version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean install
artifacts:
  files:
    - target/app-0.0.1-SNAPSHOT.jar
  discard-paths: yes
