version: "3.8"
services:
  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/frontend-deploy
    build:
      context: src/main/react-client/
    container_name: frontend
    ports:
      - 80:80

  backend:
    build:
      context: ./
    container_name: backend
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/backend-deploy
    ports:
      - 8080:8080