concurrent = 1
check_interval = 0

[[runners]]
    name = "GR134894"
    url = "https://gitlab.com/"
    token = "GR1348941TYLGzWYiWzcK9vkHRqso"
    executor = "docker"
    [runners.docker]
        tls_verify = false
        image = "ruby:2.7"
        privileged = true
        disable_cache = false
        volumes = ["/cache"]
    [runners.cache]
        Insecure = false
