  version: '3.7'

  # Define services
  services:
    mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"

      environment:
        - MONGO_INITDB_ROOT_USERNAME=rootuser
        - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
        - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
        - ME_CONFIG_MONGODB_SERVER=mongodb


  # HEROKU DEPLOYMENT:
  # - To build jar file run:
  #   docker-compose pull
  #   docker compose --env-file .env.qa up --force-recreate --build -d
  # - To look at logs from QA
  #     docker logs ultrasound-app_api_1 --follow
  # - To push to heroku run:
  #   heroku container:push web --app ultrasound-fellowship-app
